import { Reel, Collection } from "@/types/reel";

export const INITIAL_REELS: Reel[] = [
  {
    id: "reel-1",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C123456789/",
    creatorUsername: "aliabdaal",
    creatorProfileUrl: "https://instagram.com/aliabdaal",
    creatorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    caption: "5 productivity systems I actually use every single day to stay organized and calm.",
    category: "Productivity",
    subcategories: ["Time Management", "Systems", "Workflow"],
    collections: ["col-1"],
    hashtags: ["#productivity", "#systems", "#lifehacks"],
    notes: "Review the time-blocking section before planning next week.",
    isFavorite: true,
    duration: "0:45",
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), // 2 hours ago
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Ali breaks down five core daily systems: time blocking, weekly reviews, inbox zero rules, digital brain capture, and evening reflections.",
    aiKeywords: ["Productivity", "Time Blocking", "Notion", "Organization"],
    viewCount: 1420
  },
  {
    id: "reel-2",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C987654321/",
    creatorUsername: "hubermanlab",
    creatorProfileUrl: "https://instagram.com/hubermanlab",
    creatorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    caption: "3 science-backed habits that immediately improve sleep quality and deep recovery.",
    category: "Health & Fitness",
    subcategories: ["Sleep", "Neuroscience", "Recovery"],
    collections: ["col-2"],
    hashtags: ["#sleep", "#health", "#neuroscience"],
    notes: "Morning sunlight viewing within 30 mins of waking up is critical.",
    isFavorite: true,
    duration: "0:58",
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(), // 5 hours ago
    updatedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    aiSummary: "Dr. Huberman explains how morning sunlight, delayed caffeine intake, and room temperature optimization affect REM and deep sleep cycles.",
    aiKeywords: ["Sleep Architecture", "Circadian Rhythm", "Sunlight", "Caffeine"],
    viewCount: 890
  },
  {
    id: "reel-3",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C112233445/",
    creatorUsername: "techwithtim",
    creatorProfileUrl: "https://instagram.com/techwithtim",
    creatorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    caption: "Build your first autonomous AI agent in under 10 minutes using modern Python libraries.",
    category: "AI & Tech",
    subcategories: ["AI Agents", "Python", "Automation"],
    collections: ["col-3"],
    hashtags: ["#ai", "#python", "#coding", "#agents"],
    notes: "Try using the tool registry pattern described at 0:24.",
    isFavorite: false,
    duration: "0:32",
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    aiSummary: "Step-by-step tutorial on initializing an AI agent loop, equipping function calling tools, and running background task execution.",
    aiKeywords: ["AI Agents", "Python", "LLM", "Tool Calling"],
    viewCount: 2310
  },
  {
    id: "reel-4",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C556677889/",
    creatorUsername: "foodwithrahul",
    creatorProfileUrl: "https://instagram.com/foodwithrahul",
    creatorAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    caption: "10-minute paneer butter masala recipe that tastes like high-end restaurant quality!",
    category: "Food & Cooking",
    subcategories: ["Recipes", "Indian Food", "Quick Meals"],
    collections: ["col-4"],
    hashtags: ["#paneer", "#recipe", "#cooking", "#quickmeals"],
    notes: "Use cashew paste instead of cream for the authentic velvety texture.",
    isFavorite: true,
    duration: "0:40",
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    aiSummary: "Quick paneer recipe featuring pan-seared paneer cubes, spiced tomato gravy, cashew cream paste, and fresh kasuri methi finishing.",
    aiKeywords: ["Paneer", "Indian Recipe", "Dinner", "10-Minute Meal"],
    viewCount: 3100
  },
  {
    id: "reel-5",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C998877665/",
    creatorUsername: "designcourse",
    creatorProfileUrl: "https://instagram.com/designcourse",
    creatorAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    caption: "How to create better UI spacing and visual hierarchy without relying on heavy borders.",
    category: "Design",
    subcategories: ["UI/UX", "Spacing", "Typography"],
    collections: ["col-1", "col-3"],
    hashtags: ["#uidesign", "#webdesign", "#figma"],
    notes: "Rule: double container padding for section margins.",
    isFavorite: false,
    duration: "0:50",
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    aiSummary: "UI design breakdown showing how to leverage white space contrast, font weight variations, and subtle background elevation.",
    aiKeywords: ["UI Design", "Visual Hierarchy", "Spacing System", "Figma"],
    viewCount: 1840
  },
  {
    id: "reel-6",
    userId: "user-1",
    instagramUrl: "https://instagram.com/reel/C334455667/",
    creatorUsername: "athleanx",
    creatorProfileUrl: "https://instagram.com/athleanx",
    creatorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoylines.mp4",
    caption: "5 mobility exercises to fix desk posture and relieve lower back tension.",
    category: "Health & Fitness",
    subcategories: ["Posture", "Mobility", "Workout"],
    collections: ["col-2"],
    hashtags: ["#posture", "#mobility", "#fitness"],
    notes: "Do these 5 exercises before sitting down for long coding sessions.",
    isFavorite: true,
    duration: "0:38",
    createdAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 96 * 3600 * 1000).toISOString(),
    aiSummary: "Targeted posture routines for thoracic extension, hip flexor opening, and hamstring stretching for sedentary desk workers.",
    aiKeywords: ["Posture Fix", "Mobility Routine", "Back Pain", "Fitness"],
    viewCount: 4200
  }
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    name: "Ideas & Systems",
    description: "Productivity hacks, mental models, and personal workflow systems.",
    icon: "💡",
    reelIds: ["reel-1", "reel-5"],
    updatedAt: "2 hours ago",
    reelCount: 2,
  },
  {
    id: "col-2",
    name: "Workout & Health",
    description: "Daily exercises, mobility routines, and sleep optimization.",
    icon: "🏋️",
    reelIds: ["reel-2", "reel-6"],
    updatedAt: "5 hours ago",
    reelCount: 2,
  },
  {
    id: "col-3",
    name: "AI Tools & Dev",
    description: "Coding tutorials, AI agent architectures, and UI design.",
    icon: "🤖",
    reelIds: ["reel-3", "reel-5"],
    updatedAt: "1 day ago",
    reelCount: 2,
  },
  {
    id: "col-4",
    name: "Recipes & Food",
    description: "Quick dinners, paneer dishes, and healthy meal preps.",
    icon: "🍲",
    reelIds: ["reel-4"],
    updatedAt: "2 days ago",
    reelCount: 1,
  },
];
