import { Reel, Collection } from "@/types/reel";

export const INITIAL_REELS: Reel[] = [
  // 1. REEL: Productivity
  {
    id: "reel-1",
    userId: "usr-demo",
    mediaType: "reel",
    instagramUrl: "https://www.instagram.com/reel/C89210382/",
    creatorUsername: "aliabdaal",
    creatorFullName: "Ali Abdaal",
    creatorProfileUrl: "https://instagram.com/aliabdaal",
    creatorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80",
    caption: "5 productivity systems I actually use every single day to stay organized, calm, and consistent.",
    category: "Productivity",
    subcategories: ["Time Management", "Systems", "Workflow"],
    collections: ["col-1"],
    hashtags: ["#productivity", "#systems", "#lifehacks"],
    likes: "24.5K",
    commentsCount: "412",
    notes: "Review the time-blocking section before planning next week's sprint.",
    isFavorite: true,
    duration: "0:45",
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Ali breaks down five core daily systems: time blocking, weekly reviews, inbox zero rules, digital brain capture, and evening reflections.",
    aiKeywords: ["Productivity", "Time Blocking", "Notion", "Organization"],
    viewCount: 1420
  },

  // 2. SONG / AUDIO: Viral Audio Track
  {
    id: "song-1",
    userId: "usr-demo",
    mediaType: "audio",
    instagramUrl: "https://www.instagram.com/reels/audio/7819203912/",
    creatorUsername: "synthwave_collective",
    creatorFullName: "Synthwave Collective",
    creatorProfileUrl: "https://instagram.com/synthwave_collective",
    creatorAvatar: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
    audioTitle: "Midnight City Lights (Lo-Fi Chill Synth)",
    audioArtist: "Synthwave Collective • 128k Reels Used",
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3",
    caption: "Midnight City Lights • Official Instagram Audio Track. Perfect backdrop for late night workflow and coding aesthetics.",
    category: "Music & Audio",
    subcategories: ["Lo-Fi", "Synthwave", "Trending Audio"],
    collections: ["col-3"],
    hashtags: ["#trendingaudio", "#lofi", "#synthwave", "#instasong"],
    likes: "89.2K",
    commentsCount: "1.2K",
    notes: "Great background track for UI motion design showcases and product demos.",
    isFavorite: true,
    duration: "2:14",
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Trending Instagram Audio with 128K+ reels. Ambient synthwave beats ideal for aesthetic edits and product promos.",
    aiKeywords: ["Music", "Synthwave", "Trending Audio", "Beats"],
    viewCount: 3820
  },

  // 3. POST: Multi-Image Carousel (UI Architecture)
  {
    id: "post-1",
    userId: "usr-demo",
    mediaType: "post",
    instagramUrl: "https://www.instagram.com/p/C998877665/",
    creatorUsername: "designsystems.io",
    creatorFullName: "Design Systems & Tokens",
    creatorProfileUrl: "https://instagram.com/designsystems.io",
    creatorAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80",
    isCarousel: true,
    carouselImages: [
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80"
    ],
    caption: "10 Design System Rules used by Stripe and Linear to build bulletproof web applications. Swipe for complete token breakdowns.",
    category: "Design",
    subcategories: ["UI/UX", "Design Systems", "Figma"],
    collections: ["col-1", "col-3"],
    hashtags: ["#designsystems", "#uidesign", "#linear", "#stripe", "#figma"],
    likes: "18.4K",
    commentsCount: "320",
    notes: "Slide 3 spacing scale formula: Base 4px with exponential step scaling.",
    isFavorite: true,
    duration: "Carousel (3)",
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Comprehensive 3-part design tokens guide detailing 4px base spacing, optical icon alignments, and semantic color palettes.",
    aiKeywords: ["Design Systems", "UI Tokens", "Linear Design", "Figma"],
    viewCount: 2840
  },

  // 4. STORY: Active Creator Story
  {
    id: "story-1",
    userId: "usr-demo",
    mediaType: "story",
    instagramUrl: "https://www.instagram.com/stories/sam_altman/32891029384/",
    creatorUsername: "sama",
    creatorFullName: "Sam Altman",
    creatorProfileUrl: "https://instagram.com/sama",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    caption: "Behind the scenes with the research team pushing compute frontiers today. ⚡",
    category: "AI & Tech",
    subcategories: ["OpenAI", "Behind The Scenes", "Stories"],
    collections: ["col-3"],
    hashtags: ["#ai", "#compute", "#research", "#story"],
    likes: "45.1K",
    commentsCount: "890",
    notes: "Exciting sneak preview of upcoming cluster benchmarks.",
    isFavorite: false,
    duration: "Story (24h)",
    storyExpiresAt: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Instagram Story update from @sama showing real-time datacenter scaling and compute cluster operations.",
    aiKeywords: ["OpenAI", "Sam Altman", "AI Compute", "Story"],
    viewCount: 5120
  },

  // 5. REEL: Health & Fitness
  {
    id: "reel-2",
    userId: "usr-demo",
    mediaType: "reel",
    instagramUrl: "https://www.instagram.com/reel/C987654321/",
    creatorUsername: "hubermanlab",
    creatorFullName: "Dr. Andrew Huberman",
    creatorProfileUrl: "https://instagram.com/hubermanlab",
    creatorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80",
    caption: "The exact morning protocol: 10 minutes of sunlight, hydration with electrolytes, delay caffeine 90 mins.",
    category: "Health & Fitness",
    subcategories: ["Morning Routine", "Biology", "Sleep"],
    collections: ["col-2"],
    hashtags: ["#hubermanlab", "#health", "#science", "#morningroutine"],
    likes: "62.8K",
    commentsCount: "1.4K",
    notes: "Crucial protocol: Delaying morning caffeine by 90 minutes prevents afternoon energy crashes.",
    isFavorite: true,
    duration: "0:58",
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    aiSummary: "Dr. Huberman explains the adenosine clearance curve: wait 90-120 minutes post-waking before first coffee to reset cortisol rhythms.",
    aiKeywords: ["Health", "Neuroscience", "Caffeine", "Sleep"],
    viewCount: 8930
  },

  // 6. REEL: Food & Cooking
  {
    id: "reel-3",
    userId: "usr-demo",
    mediaType: "reel",
    instagramUrl: "https://www.instagram.com/reel/C567890123/",
    creatorUsername: "chef_ranveer",
    creatorFullName: "Ranveer Brar",
    creatorProfileUrl: "https://instagram.com/chef_ranveer",
    creatorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80",
    caption: "Restaurant-style Paneer Tikka in 15 minutes without a tandoor. The secret is in the mustard oil marinade!",
    category: "Food & Cooking",
    subcategories: ["Indian Cooking", "Quick Meals", "Vegetarian"],
    collections: ["col-4"],
    hashtags: ["#paneertikka", "#cooking", "#quickrecipes", "#foodie"],
    likes: "105K",
    commentsCount: "2.1K",
    notes: "Marinade: Mustard oil, roasted besan, kashmiri chilli, hung curd. Marinate for 30 mins.",
    isFavorite: false,
    duration: "0:52",
    createdAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    aiSummary: "Chef Ranveer shows the pan-smoking method with hot charcoal in a small steel katori to achieve genuine tandoori flavor at home.",
    aiKeywords: ["Paneer Tikka", "Indian Food", "Quick Recipe", "Chef Brar"],
    viewCount: 12400
  },

  // 7. SONG / AUDIO: Acoustic Chill Instrumental
  {
    id: "song-2",
    userId: "usr-demo",
    mediaType: "audio",
    instagramUrl: "https://www.instagram.com/reels/audio/4820193847/",
    creatorUsername: "acoustic_vibes",
    creatorFullName: "Acoustic Vibes Official",
    creatorProfileUrl: "https://instagram.com/acoustic_vibes",
    creatorAvatar: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=600&q=80",
    audioTitle: "Golden Hour Fingerstyle Guitar",
    audioArtist: "Acoustic Vibes • 64k Reels Used",
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3",
    caption: "Golden Hour Fingerstyle Guitar • Calming acoustic rhythm for morning reels and vlogs.",
    category: "Music & Audio",
    subcategories: ["Guitar", "Acoustic", "Morning Vibes"],
    collections: ["col-2"],
    hashtags: ["#guitar", "#acoustic", "#goldenhour", "#relaxingmusic"],
    likes: "42.3K",
    commentsCount: "510",
    notes: "Clean acoustic track for calm storytelling videos.",
    isFavorite: false,
    duration: "1:48",
    createdAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Acoustic fingerstyle guitar progression recorded in D-major. High dynamic range, suitable for voiceover mixing.",
    aiKeywords: ["Guitar", "Acoustic", "Audio Track", "Fingerstyle"],
    viewCount: 1940
  },

  // 8. POST: Photography & Landscape Post
  {
    id: "post-2",
    userId: "usr-demo",
    mediaType: "post",
    instagramUrl: "https://www.instagram.com/p/C776655443/",
    creatorUsername: "natgeo_lens",
    creatorFullName: "National Geographic Explorers",
    creatorProfileUrl: "https://instagram.com/natgeo_lens",
    creatorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    isCarousel: false,
    caption: "Dawn breaking over Yosemite Valley. High dynamic range capture with natural morning mist filtering through the pine canopy.",
    category: "Design",
    subcategories: ["Photography", "Nature", "Cinematic"],
    collections: ["col-1"],
    hashtags: ["#yosemite", "#landscape", "#naturephotography", "#natgeo"],
    likes: "92.4K",
    commentsCount: "820",
    notes: "Camera settings: Sony A7R V, 24-70mm GM II at f/8, 1/250s, ISO 100.",
    isFavorite: true,
    duration: "Post",
    createdAt: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Scenic landscape photograph of Yosemite Valley at sunrise. Notes composition, lighting ratio, and color balance.",
    aiKeywords: ["Photography", "Yosemite", "Landscape", "Sony Alpha"],
    viewCount: 4320
  },

  // 9. REEL: AI & Tech
  {
    id: "reel-4",
    userId: "usr-demo",
    mediaType: "reel",
    instagramUrl: "https://www.instagram.com/reel/C890123456/",
    creatorUsername: "clever_programmer",
    creatorFullName: "Clever Programmer",
    creatorProfileUrl: "https://instagram.com/clever_programmer",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
    caption: "Build an autonomous AI Agent in 60 seconds with Python and Function Calling.",
    category: "AI & Tech",
    subcategories: ["Python", "AI Agents", "Coding"],
    collections: ["col-3"],
    hashtags: ["#ai", "#python", "#coding", "#softwareengineer", "#agents"],
    likes: "38.9K",
    commentsCount: "810",
    notes: "Key library: LangChain / OpenAI Assistant API function definitions.",
    isFavorite: false,
    duration: "0:32",
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    aiSummary: "Step-by-step tutorial on initializing an AI agent loop, equipping function calling tools, and running background task execution.",
    aiKeywords: ["AI Agents", "Python", "LLM", "Tool Calling"],
    viewCount: 2310
  }
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    name: "Ideas & Systems",
    description: "Productivity hacks, mental models, and personal workflow systems.",
    icon: "💡",
    reelIds: ["reel-1", "reel-5"],
    updatedAt: "2 hours ago",
    reelCount: 2,
  },
  {
    id: "col-2",
    name: "Workout & Health",
    description: "Daily exercises, mobility routines, and sleep optimization.",
    icon: "🏋️",
    reelIds: ["reel-2", "reel-6"],
    updatedAt: "5 hours ago",
    reelCount: 2,
  },
  {
    id: "col-3",
    name: "AI Tools & Dev",
    description: "Coding tutorials, AI agent architectures, and UI design.",
    icon: "🤖",
    reelIds: ["reel-3", "reel-5"],
    updatedAt: "1 day ago",
    reelCount: 2,
  },
  {
    id: "col-4",
    name: "Recipes & Food",
    description: "Quick dinners, paneer dishes, and healthy meal preps.",
    icon: "🍲",
    reelIds: ["reel-4"],
    updatedAt: "2 days ago",
    reelCount: 1,
  },
];

