import { Reel, Collection } from "@/types/reel";

export const INITIAL_REELS: Reel[] = [
  // 1. REEL: Productivity
  {
    id: "reel-1",
    userId: "user-1",
    mediaType: "reel",
    instagramUrl: "https://instagram.com/reel/C123456789/",
    creatorUsername: "aliabdaal",
    creatorFullName: "Ali Abdaal",
    creatorProfileUrl: "https://instagram.com/aliabdaal",
    creatorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=600&q=80",
    caption: "5 productivity systems I actually use every single day to stay organized and calm.",
    category: "Productivity",
    subcategories: ["Time Management", "Systems", "Workflow"],
    collections: ["col-1"],
    hashtags: ["#productivity", "#systems", "#lifehacks"],
    likes: "24.5K",
    commentsCount: "412",
    notes: "Review the time-blocking section before planning next week.",
    isFavorite: true,
    duration: "0:45",
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Ali breaks down five core daily systems: time blocking, weekly reviews, inbox zero rules, digital brain capture, and evening reflections.",
    aiKeywords: ["Productivity", "Time Blocking", "Notion", "Organization"],
    viewCount: 1420
  },

  // 2. SONG / AUDIO: Viral Audio Track
  {
    id: "song-1",
    userId: "user-1",
    mediaType: "audio",
    instagramUrl: "https://instagram.com/reels/audio/7819203912/",
    creatorUsername: "synthwave_collective",
    creatorFullName: "Synthwave Collective",
    creatorProfileUrl: "https://instagram.com/synthwave_collective",
    creatorAvatar: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
    audioTitle: "Midnight City Lights (Lo-Fi Chill Synth)",
    audioArtist: "Synthwave Collective • 128k Reels Used",
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Sevish_-__nbsp_.mp3",
    caption: "Midnight City Lights • Official Instagram Audio Track. Perfect backdrop for late night workflow and coding aesthetics.",
    category: "Music & Audio",
    subcategories: ["Lo-Fi", "Synthwave", "Trending Audio"],
    collections: ["col-3"],
    hashtags: ["#trendingaudio", "#lofi", "#synthwave", "#instasong"],
    likes: "89.2K",
    commentsCount: "1.2K",
    notes: "Great background track for UI motion design showcases.",
    isFavorite: true,
    duration: "2:14",
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Trending Instagram Audio with 128K+ reels. Ambient synthwave beats ideal for aesthetic edits and product promos.",
    aiKeywords: ["Music", "Synthwave", "Trending Audio", "Beats"],
    viewCount: 3820
  },

  // 3. POST: Multi-Image Carousel (UI Architecture)
  {
    id: "post-1",
    userId: "user-1",
    mediaType: "post",
    instagramUrl: "https://instagram.com/p/C998877665/",
    creatorUsername: "designsystems.io",
    creatorFullName: "Design Systems & Tokens",
    creatorProfileUrl: "https://instagram.com/designsystems.io",
    creatorAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80",
    isCarousel: true,
    carouselImages: [
      "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80"
    ],
    caption: "10 Design System Rules used by Stripe and Linear to build bulletproof web applications. Swipe for complete token breakdowns.",
    category: "Design",
    subcategories: ["UI/UX", "Design Systems", "Figma"],
    collections: ["col-1", "col-3"],
    hashtags: ["#designsystems", "#uidesign", "#linear", "#stripe", "#figma"],
    likes: "18.4K",
    commentsCount: "320",
    notes: "Slide 3 spacing scale formula: Base 4px with exponential step scaling.",
    isFavorite: true,
    duration: "Carousel (3)",
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Comprehensive 3-part design tokens guide detailing 4px base spacing, optical icon alignments, and semantic color palettes.",
    aiKeywords: ["Design Systems", "UI Tokens", "Linear Design", "Figma"],
    viewCount: 2840
  },

  // 4. STORY: Active Creator Story
  {
    id: "story-1",
    userId: "user-1",
    mediaType: "story",
    instagramUrl: "https://instagram.com/stories/sam_altman/32891029384/",
    creatorUsername: "sama",
    creatorFullName: "Sam Altman",
    creatorProfileUrl: "https://instagram.com/sama",
    creatorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    caption: "Behind the scenes with the research team pushing compute frontiers today. ⚡",
    category: "AI & Tech",
    subcategories: ["OpenAI", "Behind The Scenes", "Stories"],
    collections: ["col-3"],
    hashtags: ["#ai", "#compute", "#research", "#story"],
    likes: "45.1K",
    commentsCount: "890",
    notes: "Exciting sneak preview of upcoming cluster benchmarks.",
    isFavorite: false,
    duration: "Story (24h)",
    storyExpiresAt: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Instagram Story update from @sama showing real-time datacenter scaling and compute cluster operations.",
    aiKeywords: ["OpenAI", "Sam Altman", "AI Compute", "Story"],
    viewCount: 5120
  },

  // 5. REEL: Health & Fitness
  {
    id: "reel-2",
    userId: "user-1",
    mediaType: "reel",
    instagramUrl: "https://instagram.com/reel/C987654321/",
    creatorUsername: "hubermanlab",
    creatorFullName: "Dr. Andrew Huberman",
    creatorProfileUrl: "https://instagram.com/hubermanlab",
    creatorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80",
    caption: "3 science-backed habits that immediately improve sleep quality and deep recovery.",
    category: "Health & Fitness",
    subcategories: ["Sleep", "Neuroscience", "Recovery"],
    collections: ["col-2"],
    hashtags: ["#sleep", "#health", "#neuroscience"],
    likes: "32.1K",
    commentsCount: "589",
    notes: "Morning sunlight viewing within 30 mins of waking up is critical.",
    isFavorite: true,
    duration: "0:58",
    createdAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    aiSummary: "Dr. Huberman explains how morning sunlight, delayed caffeine intake, and room temperature optimization affect REM and deep sleep cycles.",
    aiKeywords: ["Sleep Architecture", "Circadian Rhythm", "Sunlight", "Caffeine"],
    viewCount: 890
  },

  // 6. SONG / AUDIO: Viral Beat
  {
    id: "song-2",
    userId: "user-1",
    mediaType: "audio",
    instagramUrl: "https://instagram.com/audio/9948210384/",
    creatorUsername: "aesthetic_beats",
    creatorFullName: "Aesthetic Beats",
    creatorProfileUrl: "https://instagram.com/aesthetic_beats",
    creatorAvatar: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80",
    audioTitle: "Golden Hour Vibes (Acoustic Sunset)",
    audioArtist: "Aesthetic Beats • 340k Reels Used",
    audioUrl: "https://commondatastorage.googleapis.com/codeskulptor-demos/DDR_assets/Kangaroo_MusiQue_-_The_Neverending_Story.mp3",
    caption: "Golden Hour Vibes • Warm acoustic guitar progression trending across lifestyle and recipe reels.",
    category: "Music & Audio",
    subcategories: ["Acoustic", "Chill", "Viral Sounds"],
    collections: ["col-4"],
    hashtags: ["#acoustic", "#audio", "#goldenhour", "#chillvibes"],
    likes: "142K",
    commentsCount: "2.4K",
    notes: "Warm sunset acoustic background.",
    isFavorite: false,
    duration: "1:48",
    createdAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date().toISOString(),
    aiSummary: "Acoustic fingerpicking guitar audio track with over 340,000 uses across Instagram reels.",
    aiKeywords: ["Guitar", "Acoustic", "Viral Audio", "Golden Hour"],
    viewCount: 6400
  },

  // 7. POST: Single Photo Post (Culinary)
  {
    id: "post-2",
    userId: "user-1",
    mediaType: "post",
    instagramUrl: "https://instagram.com/p/C556677889/",
    creatorUsername: "foodwithrahul",
    creatorFullName: "Chef Rahul Verma",
    creatorProfileUrl: "https://instagram.com/foodwithrahul",
    creatorAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    caption: "The secret to restaurant-style velvety paneer butter masala is roasting whole spices in cold pressed mustard oil first. Full step-by-step recipe in comments! 🥘",
    category: "Food & Cooking",
    subcategories: ["Recipes", "Indian Food", "Quick Meals"],
    collections: ["col-4"],
    hashtags: ["#paneer", "#recipe", "#cooking", "#quickmeals"],
    likes: "15.9K",
    commentsCount: "428",
    notes: "Use cashew paste instead of cream for the authentic velvety texture.",
    isFavorite: true,
    duration: "Photo Post",
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    aiSummary: "Quick paneer recipe featuring pan-seared paneer cubes, spiced tomato gravy, cashew cream paste, and fresh kasuri methi finishing.",
    aiKeywords: ["Paneer", "Indian Recipe", "Dinner", "10-Minute Meal"],
    viewCount: 3100
  },

  // 8. REEL: AI & Tech
  {
    id: "reel-3",
    userId: "user-1",
    mediaType: "reel",
    instagramUrl: "https://instagram.com/reel/C112233445/",
    creatorUsername: "techwithtim",
    creatorFullName: "Tim Ruscica",
    creatorProfileUrl: "https://instagram.com/techwithtim",
    creatorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
    caption: "Build your first autonomous AI agent in under 10 minutes using modern Python libraries.",
    category: "AI & Tech",
    subcategories: ["AI Agents", "Python", "Automation"],
    collections: ["col-3"],
    hashtags: ["#ai", "#python", "#coding", "#agents"],
    likes: "19.3K",
    commentsCount: "284",
    notes: "Try using the tool registry pattern described at 0:24.",
    isFavorite: false,
    duration: "0:32",
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    lastViewedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    aiSummary: "Step-by-step tutorial on initializing an AI agent loop, equipping function calling tools, and running background task execution.",
    aiKeywords: ["AI Agents", "Python", "LLM", "Tool Calling"],
    viewCount: 2310
  }
];

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    name: "Ideas & Systems",
    description: "Productivity hacks, mental models, and personal workflow systems.",
    icon: "💡",
    reelIds: ["reel-1", "reel-5"],
    updatedAt: "2 hours ago",
    reelCount: 2,
  },
  {
    id: "col-2",
    name: "Workout & Health",
    description: "Daily exercises, mobility routines, and sleep optimization.",
    icon: "🏋️",
    reelIds: ["reel-2", "reel-6"],
    updatedAt: "5 hours ago",
    reelCount: 2,
  },
  {
    id: "col-3",
    name: "AI Tools & Dev",
    description: "Coding tutorials, AI agent architectures, and UI design.",
    icon: "🤖",
    reelIds: ["reel-3", "reel-5"],
    updatedAt: "1 day ago",
    reelCount: 2,
  },
  {
    id: "col-4",
    name: "Recipes & Food",
    description: "Quick dinners, paneer dishes, and healthy meal preps.",
    icon: "🍲",
    reelIds: ["reel-4"],
    updatedAt: "2 days ago",
    reelCount: 1,
  },
];
